### ISSUE TITLE
Markdown does not work if '[' and/or ']' characters are included in the link title

### ISSUE THREAD

**Issue by Luke47** [xing/XNGMarkdownParser#13]
If a link title contains square brackets, e.g.

`[Test [Meta Issue] ] (link)`

the markdown does not work properly (the [ and ] are returned non-escaped by our backend).

What would be the easiest solution to solve this on the side of iOS? (We would like to avoid changing server-side stuff).

Thank you very much! :)

**Comment by pietbrauer** [comment]
Yep, that is a known issue and we haven't found a workaround, yet.

**Comment by gskbyte** [comment]
You can, however, escape them using backslashes: ``[link \[meta issue\] bla](www.link.com)``

**Comment by Luke47** [comment]
@gskbyte : Yep, that's what I did now - thank you for your help!

**Comment by pietbrauer** [comment]
@Luke47 Can be closed then?

**Comment by Luke47** [comment]
Yes, thank you!
