### ISSUE TITLE
How to change the grammar?

### ISSUE THREAD

**Issue by Luke47** [xing/XNGMarkdownParser#14]
I know there is a .grammar file in the repository, but how do I change the content of it?

I've used Cocoapods to install the parser and can't find the file in the local folder.

Thank you!

**Comment by pietbrauer** [comment]
If you change the grammar you should run [`generate.sh`](https://github.com/xing/XNGMarkdownParser/blob/master/grammar/generate.sh) afterwards. That will regenerate the Objective-C Grammar file.
