### ISSUE TITLE
Multiline code blocks don't parsed

### ISSUE THREAD

**Issue by nexplus** [xing/XNGMarkdownParser#16]
Hi!
I have troubles to recognise and highlight multiline code blocks using this component.
I mean code blocks like with "```" in begin and the same on end:

```
@interface ChatRoom : NSObject

@property (nonatomic) enum RoomType type;
@property (nonatomic, strong) NSDate *createdDateTime;
@property (nonatomic, strong) NSMutableArray *membersIdsArray;

@end
```

Inline code recognition works good (something like ` var i=5; ` with symbol "`" in the begin and end ), but multiline not at all((

Thanks.

**Comment by gskbyte** [comment]
Hello, sorry for the late answer. I just had a look at the grammar and I saw that we are only supporting inline code blocks (https://github.com/xing/XNGMarkdownParser/blob/master/grammar/markdown.grammar#L50). It should be easy to add support for code blocks, do you feel like making a pull request? Thanks!

**Comment by nexplus** [comment]
Thanks for answer.
I am not very familiar with flex and so on, so it will need for me to setup tools for generating grammar and so on, I just ask cause I looks like already have all this stuff.
