### ISSUE TITLE
Links clickable?

### ISSUE THREAD

**Issue by chriscdn** [xing/XNGMarkdownParser#20]
The library looks promising, but links are highlighted and not clickable.  Is this not a feature or do links need to be explicitly enabled somehow?

**Comment by Luke47** [comment]
You mean you want to open Safari when the user taps a URL? The easiest solution would be to put your text into a UITextview. It has built-in link support :)

**Comment by chriscdn** [comment]
Hi Lukas.. thanks. I realise now XNGMarkdownParser and TTTAttributeLabel solve two different problems.  I have it working.
